name: bf_theme
description: "BOSSFEVER flutter theme."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1-alpha.3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true